### ISSUE TITLE
0.4.0 release has missing pom from maven central

### ISSUE THREAD

**Issue by gaborgsomogyi** [alibaba/pemja#38]
I've just analyzed through why `pemja 0.4.0` is not found and the reason is that:
 * `0.3.0` has pom inside: https://repo.maven.apache.org/maven2/com/alibaba/pemja/0.3.0/
 <img width="616" alt="Screenshot 2023-09-15 at 11 05 56" src="https://github.com/apache/flink/assets/18561820/19149d2b-6aeb-49db-9fe9-46b151615aa4">

 * `0.4.0` has `no` pom inside: https://repo.maven.apache.org/maven2/com/alibaba/pemja/0.4.0/
<img width="612" alt="Screenshot 2023-09-15 at 11 06 36" src="https://github.com/apache/flink/assets/18561820/c1229b6e-71c7-4c14-88b9-d3cf27362e5f">

**Comment by HuangXingBo** [comment]
I will release 0.4.1 asap.
